INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('mstollard7','aphysicx',16,37,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('lfontenotg','dmein13',24,89,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('krannie1n','wratchfordo',23,87,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('lfontenotg','lshreve15',22,27,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('rarrowsmithe','aphysicx',39,24,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('nzannollij','pmacgilfoyle1a',19,80,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('slurcock5','nhourstan10',9,44,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('kdaout18','lshreve15',22,43,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('lgaddas1','eskamal17',32,47,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('dantunes8','dledgerl',31,47,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('rhillan1b','boscanlanf',34,48,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('dgodfrayw','jmatisset',21,98,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('mlawrey1j','aphysicx',6,7,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('achellingworth1g','eskamal17',17,38,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('mpollock19','ejulyanr',33,57,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('mstollard7','nhourstan10',9,55,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('msodeau16','mpollock19',20,48,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('kdaout18','nhourstan10',9,79,'self pickup','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('bkaubisch2','lmiddletonu',37,82,'delivery','pending');
INSERT INTO transactions(b_id,s_id,p_id,qty,delivery,status) VALUES ('pmacgilfoyle1a','mlawrey1j',10,28,'delivery','pending');
